
rem Remove EQASCOM ini files
del "%APPDATA%\EQMOD\EQMOD.INI"
del "%APPDATA%\EQMOD\ALIGN.INI"
del "%APPDATA%\EQMOD\JOYSTICK.INI"

rem Remove Simulator ini files
del "%APPDATA%\EQMOD_SIM\EQMOD.INI"
del "%APPDATA%\EQMOD_SIM\ALIGN.INI"
del "%APPDATA%\EQMOD_SIM\JOYSTICK.INI"

pause
